package main.java.screen;



    //Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

    public class UsernameScreen extends JPanel {
        private JTextField jcomp1;
        private JLabel jcomp2;

        public UsernameScreen() {
            //construct components
            jcomp1 = new JTextField (5);
            jcomp2 = new JLabel ("Username");

            //adjust size and set layout
            setPreferredSize (new Dimension (311, 146));
            setLayout (null);

            //add components
            add (jcomp1);
            add (jcomp2);

            //set component bounds (only needed by Absolute Positioning)
            jcomp1.setBounds (55, 65, 205, 45);
            jcomp2.setBounds (55, 25, 100, 25);
        }


        public static void main (String[] args) {
            JFrame frame = new JFrame("MyPanel");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new UsernameScreen());
            frame.pack();
            frame.setVisible(true);
        }

        public String getUsername() {
            return jcomp1.getText();
        }
    }
