package main.java.screen;



    //Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import main.java.Principale.Jeu;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

    public class UsernameScreen extends JFrame {
        private JTextField jcomp1;
        private JLabel jcomp2;
        private JPanel jcomp3;

        private JButton jcomp4;

        private Jeu jeu;

        public UsernameScreen(Jeu jeu) {
            this.jeu = jeu;

            setTitle("Select username");
            setLocationRelativeTo(null);

            setResizable(false);

            //Construction des composants de la fenêtre
            jcomp1 = new JTextField (5);
            jcomp2 = new JLabel ("Username");
            jcomp3 = new JPanel (null);
            jcomp4 = new JButton ("Valider");

            //Changement de la taille de la fenêtre
            jcomp3.setPreferredSize (new Dimension (311, 146));
            jcomp3.setLayout (null);

            //ajout de l'action du bouton valider
            jcomp4.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (jcomp1.getText().length() > 0) {
                        jeu.setNamePlayer(jcomp1.getText());
                        jeu.setGameState(1);
                        jeu.demarreJeu();
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Veuillez entrer un nom d'utilisateur");
                    }
                }
            });

            //Ajout des composants dans la fenêtre
            jcomp3.add(jcomp1);
            jcomp3.add(jcomp2);
            jcomp3.add(jcomp4);
            this.getContentPane().add(jcomp3);
            this.pack();
            this.setVisible(true);

            //Mise en place des composants
            jcomp1.setBounds (55, 65, 205, 25);
            jcomp2.setBounds (120, 25, 100, 25);
            jcomp4.setBounds (105, 115, 100, 25);
        }
    }
